- block:
    - name: install webserver packages for generic importer
      package: name={{ item }} state=present
      with_items:
        - "{{ webserver_package_name }}"
        - "{{ wsgi_package_name }}"
      environment: "{{ proxy_env }}"

    - name: copy generic importer httpd config file to target
      template:
        src: "httpd-generic-importer.conf.j2"
        dest: "{{ http_conf_dir }}/{{ product_name }}-generic-importer.conf"
        owner: root
        group: root

    - name: enable apache modules proxy proxy_http ssl
      apache2_module:
        state: present
        name: "{{ item }}"
      loop: "{{ apache2_required_modules }}"

    - name: create apache certificates
      include_role:
        name: openssl-cert
      vars:
        openssl_cert_path: /etc/apache2/ssl
        openssl_user: root
        openssl_private_key: "{{ openssl_cert_path }}/server.key"
        openssl_csr: "{{ openssl_cert_path }}/server.csr"
        openssl_country: DE
        openssl_state: Hessen
        openssl_location: Frankfurt
        openssl_organization: Cactus eSecurity
        openssl_email_address: "fworch@cactus.de"
        openssl_cert: "{{ openssl_cert_path }}/server.crt"
      when: installation_mode == "new"

    - name: copy cert to /etc/ssl/certs/ to make it acceptable
      copy:
        src: "/etc/apache2/ssl/server.crt"
        dest: "/etc/ssl/certs/"
        remote_src: true
      when: installation_mode == "new"

    - name: enable {{ product_name }} generic importer apache site
      command: "a2ensite {{ product_name }}-generic-importer"
      register: testoutput

    - name: add generic importer port to apache
      lineinfile:
        path: "/etc/apache2/ports.conf"
        line: "Listen {{ proxy_importer_web_listener_port }}"
        insertafter: "<IfModule ssl_module>"

    - name: restart apache
      service:
       name: "{{ webserver_package_name }}"
       state: restarted

  become: true
  environment: "{{ proxy_env }}"
