importer_home: "{{ fworch_home }}/importer"
generic_gateway_importer_dir: "{{ fworch_home }}/generic-gateway-importer"
generic_gateway_importer_start_dir: "{{ generic_gateway_importer_dir }}/FWO.GenericGatewayImporter"
generic_gateway_importer_service_name: "{{ product_name }}-generic-importer"
generic_gateway_importer_listen_uri: "http://0.0.0.0:{{ generic_gateway_importer_listen_port }}/"
generic_gateway_importer_db_user: "fworchimporter"
generic_gateway_importer_schema: "generic_gateway"
apache_generic_importer_timeout: 14400
